theme: jekyll-theme-minimal
title: Deep Learning Training
description: Training resources for an introduction to deep learning using Pytorch.
logo: https://avatars.githubusercontent.com/rob-fletcher