name: dltraining
dependencies:
    - python=3.6.9
    - pytorch::pytorch=1.3.1
    - pytorch::torchvision=0.4.2
    - jupyterlab
    - pip
    - pip:
        - pytorch-lightning==0.5.3.2
        - git+https://EsriASA:ccgkkdhsr5lgla5igcxrkgzvomae2whx5qfnikhvlhvxq73pu3ba@dev.azure.com/EsriASA/arcgis.slurm/_git/arcgis.slurm@master
        - matplotlib
        - jupyter_contrib_nbextensions