name: dltraining
dependencies:
  - python=3.8
  - pytorch::pytorch=1.11.0
  - pytorch::torchvision=0.12
  - jupyterlab
  - pip
  - pip:
      - pytorch-lightning==1.6.4
      - matplotlib
      - jupyter_contrib_nbextensions
